import { DocPage } from '@/types/docs';

export const verificationQrDoc: DocPage = {
  slug: ['verification', 'qr-verification'],
  title: 'QR Code & In-Person Verification',
  description: 'Step-by-step guide for scanning dynamic QR codes, handling rotating time-based tokens, and preventing screenshot fraud in physical environments.',
  section: 'Verification Portal',
  lastUpdated: 'August 2026',
  badge: 'v1.0',
  toc: [
    { id: 'how-qr-works', title: 'How Dynamic QR Codes Work', level: 2 },
    { id: 'scanning-process', title: 'The In-Person Scanning Process', level: 2 },
    { id: 'anti-screenshot-protection', title: 'Anti-Screenshot & Anti-Fraud Protection', level: 2 },
    { id: 'offline-grace-modes', title: 'Network Fault Tolerance', level: 2 },
  ],
  content: [
    {
      type: 'paragraph',
      text: 'Physical verification with SyncNexa provides airtight protection against counterfeit student cards and shared discount screenshots using cryptographically rotating dynamic QR codes.',
    },
    {
      type: 'heading',
      level: 2,
      id: 'how-qr-works',
      text: 'How Dynamic QR Codes Work',
    },
    {
      type: 'paragraph',
      text: 'Static QR codes (such as a printed barcode or static image) are vulnerable to screenshot sharing. SyncID QR codes are dynamic and ephemeral: every QR code generated by the student\'s device contains an encrypted challenge payload that expires within **30 seconds**.',
    },
    {
      type: 'heading',
      level: 2,
      id: 'scanning-process',
      text: 'The In-Person Scanning Process',
    },
    {
      type: 'steps',
      steps: [
        {
          title: '1. Student Opens SyncID App',
          content: 'The student opens their SyncID mobile app and selects the credential they wish to present (e.g. *Student Enrollment Proof*). The app generates a dynamic rotating QR code.',
        },
        {
          title: '2. Verifier Scans the QR Code',
          content: 'The store cashier or venue staff member points the Verification Portal camera scanner at the student\'s screen.',
        },
        {
          title: '3. Instant Proof Validation',
          content: 'The Verification Portal sends the encrypted payload to the SyncNexa Verification Service, which verifies the institutional signature and zero-knowledge proof.',
        },
        {
          title: '4. Instant Visual & Audio Feedback',
          content: 'The portal displays an animated green checkmark with the verified university name and emits a confirmation chime for hands-free cashier workflows.',
        },
      ],
    },
    {
      type: 'heading',
      level: 2,
      id: 'anti-screenshot-protection',
      text: 'Anti-Screenshot & Anti-Fraud Protection',
    },
    {
      type: 'callout',
      variant: 'security',
      title: 'One-Time Nonce & Expiration',
      text: 'If a student takes a screenshot of their QR code and sends it to a friend, the QR code will have already expired before the friend can present it at the register. Replay attempts are instantly rejected by the verification gateway.',
    },
    {
      type: 'heading',
      level: 2,
      id: 'offline-grace-modes',
      text: 'Network Fault Tolerance',
    },
    {
      type: 'paragraph',
      text: 'In environments with intermittent connectivity (e.g., underground subway transit, outdoor music festivals), the Verification Portal caches trusted university public keys locally in browser IndexedDB, allowing offline cryptographic validation of time-stamped signatures.',
    },
  ],
};
